version: '3.10'
services:
  web:
    build: ./
    command: gunicorn django_market.wsgi:application --bind 0.0.0.0:8000 --reload -w 4

    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.db
volumes:
  postgres_data: